# 服务
server:
  port: 8081
#dubbo相关
dubbo:
  #  应用相关
  application:
    name: user-service-consumer
    logger: slf4j
  #    注册中心
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  #    协议
  protocol:
    name: dubbo
    port: 28081
  monitor:
    protocol: registry

